---
title: "Spatial Data Science with R. Day 2."
author: "Edzer Pebesma"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Geostatistics

Geostatistics is concerned with _field_ variables, i.e. variables that 

* vary continuously over space, or space/time
* can meaningfully be _interpolated_ (predicted) at unobserved locations

That is, _not_ with marked point patterns, such as

* tree stem diameters
* coal power plant emissions

although both share the property of being "xyz" data (point coordinates + attributes)

## Overview

* spatial correlation: (semi)variogram, auto-covariogram, auto-correllogram
* spatial prediction:
    * when is spatial prediction meaningful? fields and point processes.
    * stationarity, ergodicity
    * prediction errors
    * change of support
* exporartory data analysis: distance distributions, the h-scatterplot
* computing and modelling variograms
* kriging prediction
* regression models with stationary residuals

----

* multivariable geostatistics: co-kriging
* modelling non-stationary processes: transformation, stratification
* spatiotemporal geostatistics
* machine learning approaches to spatial prediction


## spatial prediction:

Given $n$ observations $z(x_1), ...,z(x_n)$ we assume a model, 
$Z(x) = Z(x_1),...,Z(x_n)$ where $Z$ is random, and $x$ is not.

Spatial prediction (Kriging) is concerned with predicting unobserved values $Z(x_0)$, by using a linear predictor
$$\hat{Z}(x_0) = \sum_{i=1}^n \lambda_i Z(x_i)$$
where weights are chosen such that $E(\hat{Z}(x_0)) = E(Z(x_0))$ and $Var(\hat{Z}(x_0)-Z(x_0))$ is minimal.

This is meaningful for point patterns only if there is a missing value, i.e. if $x_0$ has a tree for which we don't know the tree diameter. For field variables, such as air temperature, we have missing values pretty much _everywhere_, and thus can estimate $Z(x)$ over a continuous _surface_.

## Stationarity, ergodicity

For finding the Kriging weights, we need to know all (co)variances of and between the $Z(x_i)$ and $Z(x_0)$. This can only be done by making stationarity assumptions.
E.g. second order stationarity involves

* stationarity of the mean: $E(Z(x)) = m$
* stationarity of the variance: $E(Z(x)-m)^2 = C(0)$
* stationarity of the covariance: $E(((Z(x)-m)(Z(x+h)-m))) = C(h)$

or the slightly weaker intrinsic stationarity works on increments:

* mean: $E(Z(x)-Z(x+h)) = 0$
* variance: $E(Z(x)-Z(x+h))^2 = 2 \gamma(h)$

----

$C(h)$ is called the covariogram,
$\gamma(h)$ is called the semivariogram, or variogram.

For second order stationary fields, i.e. $C(0) < \infty$, we have
$$C(0) - C(h) = \gamma(h)$$
and the _correlogram_ defined as $C(h)/C(0)$.

**Ergodicity** involves the esimation of $\gamma(h)$, or $C(h)$. It (very) roughly means that the data must be able to contain the information sought. This is not the case when 

* Using temperature data from Munich to estimate $\gamma(h)$ for distances larger than a few kilometers, as would be needed for interpolating temperatures over Germany 
* there is no repetition or regularity, but  e.g. composition of different processes with very different properties in the data set

## prediction errors

Given the kriging predictor, we also obtain a kriging error
$$\sigma(x_0) = E((\hat{Z}(x_0)-Z(x_0))^2)$$
which 

* is an _average_ measure of error, given that all assumptions are met
* only depends on (co)variances, and not on data values (i.e., is only configuration dependent)
* will be Normally distributed if $Z(s)$ is multivariate Gaussian
* (ordinary, universal) kriging involves the assumption that the mean process ($m$) is unknown, but $\gamma(h)$ is known

## Change of support

Change of support involves estimating block averages of the form
$$\frac{1}{|A|}\int_A Z(u)du$$

or other aggregations of the form
$$\frac{1}{|A|}\int_A g(Z(u))du$$
which could, for instance, estimate the fraction of an area for which a certain threshold is exceeded, if $g(\cdot)$ is an indicator function.

The integrals are usually approximated by a weighted or unweighted sum; the linear average is obtained by _block kriging_, the non-linear by

1. _stochastic_ simulation of $Z$ at the point support, 
2. then applying $g()$, 
3. then spatially aggregating 

## spatial correlation: (semi)variogram, auto-covariogram, auto-correllogram 

* exporartory data analysis: distance distributions, the h-scatterplot
* computing and modelling variograms
* kriging prediction
* regression models with stationary residuals

----

* multivariable geostatistics: co-kriging
* modelling non-stationary processes: transformation, stratification
* spatiotemporal geostatistics
* machine learning approaches to spatial prediction